import type { ImageAttachmentRef } from "../../../src/index.js";
import type { UiEventEnvelope } from "../../../ui/contracts.js";
import { createConversationRunState, createSubmittedConversationRunState, reduceConversationRun, type ConversationRunState } from "../../../ui/conversation-run.js";

export interface ChatItem { readonly id: string; readonly role: "user" | "assistant"; readonly content: string; readonly attachments?: readonly ImageAttachmentRef[]; readonly run?: ConversationRunState; }
export function beginSubmittedMessages(items: readonly ChatItem[], userId: string, content: string, attachments: readonly ImageAttachmentRef[], submissionId: string, sessionId?: string): readonly ChatItem[] { return [...items, { id: userId, role: "user", content, ...(attachments.length ? { attachments } : {}) }, { id: `pending:${submissionId}`, role: "assistant", content: "", run: createSubmittedConversationRunState(submissionId, sessionId) }]; }
export function startSubmittedRun(items: readonly ChatItem[], submissionId: string, runId: string, sessionId: string): readonly ChatItem[] { return items.map((item) => item.id === `pending:${submissionId}` ? { ...item, id: runId, run: createConversationRunState(runId, sessionId) } : item); }
export function failSubmittedRun(items: readonly ChatItem[], submissionId: string, message: string): readonly ChatItem[] { return items.map((item) => item.id === `pending:${submissionId}` ? update(item, { kind: "error", message }) : item); }
export function appendAssistantDelta(items: readonly ChatItem[], runId: string, delta: string): readonly ChatItem[] { const index = items.findIndex((item) => item.id === runId); if (index < 0) { const run = reduceConversationRun(createConversationRunState(runId, "unknown"), { kind: "delta", delta }); return [...items, { id: runId, role: "assistant", content: run.text, run }]; } return items.map((item) => item.id === runId ? update(item, { kind: "delta", delta }) : item); }
export function applyAssistantEvent(items: readonly ChatItem[], event: Extract<UiEventEnvelope["payload"], { kind: "agent.event" }>["event"]): readonly ChatItem[] { if ("delivery" in event) return items; const index = items.findIndex((item) => item.id === event.runId); if (index < 0) { const run = reduceConversationRun(createConversationRunState(event.runId, event.sessionId), { kind: "agent-event", event }); return [...items, { id: event.runId, role: "assistant", content: run.text, run }]; } return items.map((item) => item.id === event.runId ? update(item, { kind: "agent-event", event }) : item); }
export function finalizeAssistant(items: readonly ChatItem[], runId: string, status: string, finalText: string): readonly ChatItem[] { return items.map((item) => item.id === runId ? update(item, { kind: "finish", status, finalText }) : item); }
export function sessionMessages(value: unknown): readonly ChatItem[] { const entries = (value as { entries?: Array<{ id: string; message: { kind: string; content?: string; attachments?: readonly ImageAttachmentRef[] } }> }).entries ?? []; return entries.filter((entry) => (entry.message.kind === "user" || entry.message.kind === "assistant") && typeof entry.message.content === "string").map((entry) => ({ id: entry.id, role: entry.message.kind as "user" | "assistant", content: entry.message.content ?? "", ...(entry.message.attachments?.length ? { attachments: entry.message.attachments } : {}) })); }
export function preserveLiveAssistant(history: readonly ChatItem[], current: readonly ChatItem[]): readonly ChatItem[] { const live = current.filter((item) => item.role === "assistant" && item.run && ["waiting", "streaming", "tool"].includes(item.run.status)); return [...history, ...live.filter((item) => !history.some((entry) => entry.id === item.id))]; }
function update(item: ChatItem, action: Parameters<typeof reduceConversationRun>[1]): ChatItem { const run = reduceConversationRun(item.run ?? createConversationRunState(item.id, "unknown"), action); return { ...item, content: run.text, run }; }
